final/config/routes.rb
Rails.application.routes.draw do
  resources :todos
  devise_for :users

  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

final/app/models/todo.rb
class Todo < ApplicationRecord
  enum status: [:created, :done]

  validates :date, presence: true
  validates :due_time, presence: true
  validates :description, presence: true
  validates :status, presence: true

  belongs_to :user
end

final/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_format_of :password, with: /\A(?=.*[a-z])(?=.*[0-9]).{6,}\z/

  has_many :todos
end

final/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected
    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    end
end

final/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.where(user: current_user) || []
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    if Todo.statuses.has_key?(todo_params[:status])
      @todo = Todo.new(todo_params)
    else
      @todo = Todo.new
    end
    @todo.user = current_user

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if Todo.statuses.has_key?(todo_params[:status]) && @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:date, :due_time, :description, :status)
    end
end

final/app/helpers/application_helper.rb
module ApplicationHelper
end

final/app/helpers/todos_helper.rb
module TodosHelper
end

final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

final/app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <div class="input-group date">
      <%= form.text_field :date, id: :todo_date %>
    </div>
  </div>

  <div class="field" >
    <%= form.label :due_time %>
    <div class="input-group date">
      <%= form.text_field :due_time, id: :todo_due_time %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :todo_description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select(:status, Todo.statuses.keys.to_a, {selected: :created}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(function() {
    var now = new Date();
    <% if todo.date %>
    var date = new Date(Date.parse("<%= todo.date.iso8601 %>"));
    <% else %>
    var date = now;
    <% end %>
    <% if todo.due_time %>
    var due_time = new Date(Date.parse("<%= todo.due_time.iso8601 %>"));
    <% else %>
    var due_time = now;
    <% end %>

    if (date >= now) {
      $('#todo_date').datetimepicker({
        format: 'YYYY-MM-DD HH:mm:ss',
        minDate: now,
        defaultDate: date
      });
    } else {
      $('#todo_date').prop('disabled', true);
    }

    if (due_time >= now) {
      $('#todo_due_time').datetimepicker({
        format: 'YYYY-MM-DD HH:mm:ss',
        minDate: now,
        defaultDate: due_time
      });
    } else {
      $('#todo_due_time').prop('disabled', true);
    }

  });
</script>

final/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

final/app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table border="0" cellspacing="5" cellpadding="5">
  <tbody>
    <tr>
      <td>Date:</td>
      <td>
        <div class="input-group date">
          <input type="text" id="todo_date" name="todo_date">
        </div>
      </td>
    </tr>
  </tbody>
</table>

<table class="table table-striped" id="todo-list">
  <thead>
    <tr>
      <th>Description</th>
      <th>Date</th>
      <th>Due time</th>
      <th>Status</th>
      <th>Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.description %></td>
        <td><%= todo.date.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%= todo.due_time.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%= todo.status %></td>
        <td>
          <span><%= link_to 'Show', todo %></span>
          <span><%= link_to 'Edit', edit_todo_path(todo) %></span>
          <span><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

<script type="text/javascript">
  $(function() {
    $('#todo-list').DataTable({
      order: [[2, 'asc']]
    });

    var min_date = new Date();
    min_date.setMonth(min_date.getMonth() - 1);
    var max_date = new Date();
    max_date.setMonth(max_date.getMonth() + 1);
    $('#todo_date').datetimepicker({
      format: 'YYYY-MM-DD',
      minDate: min_date,
      maxDate: max_date
    });

    $.fn.dataTable.ext.search.push(function(settings, data, dataIndex) {
      var filter_date = $('#todo_date').data('date');
      var date = data[1];
      console.log('[FilterDate] ' + filter_date);
      console.log('[CurrentDate] ' + date);
      return !filter_date || date.indexOf(filter_date) != -1;
    });

    $('#todo_date').on('dp.change', function(e) {
      var todo_list = $('#todo-list').DataTable();
      todo_list.draw();
    });
  });
</script>

final/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

final/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @todo.date %>
</p>

<p>
  <strong>Due time:</strong>
  <%= @todo.due_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>