assignment4/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :categories
	resources :posts

	root 'posts#index'
end

assignment4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

assignment4/app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

	validates :name, presence: true, length: { maximum: 500 }
end

assignment4/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  validates :title, presence: true, length: { maximum: 500 }
end

assignment4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

assignment4/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_url(@category)
    else
      render 'new'
    end
	end

	def edit
		@category = Category.find_by(id: params[:id])
	end

	def update
    @category = Category.find_by(id: params[:id])
    if @category.update(category_params)
      redirect_to category_url(@category)
    else
      render 'edit'
    end
	end

  def show
    @category = Category.find_by(id: params[:id])
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

assignment4/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
		@categories = Category.all
	end

	def create
		@post = Post.new(post_params)
		if params[:post].has_key?(:category) and !params[:post][:category].empty?
			@post.category = Category.find_by(id: params[:post][:category].to_i)
		end

		if @post.save
      redirect_to post_url(@post)
    else
    	@categories = Category.all
      render 'new'
    end
	end

	def edit
		@post = Post.find_by(id: params[:id])
		@categories = Category.all
	end

	def update
		@post = Post.find_by(id: params[:id])
		if params[:post].has_key?(:category) and !params[:post][:category].empty?
			@post.category = Category.find_by(id: params[:post][:category].to_i)
		end

		if @post.update(post_params)
      redirect_to post_url(@post)
		else
    	@categories = Category.all
      render 'edit'
		end
	end

	def show
		@post = Post.find_by(id: params[:id])
	end

	def destory
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_url
	end

  private
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

assignment4/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment4/app/helpers/categories_helper.rb
module CategoriesHelper
end

assignment4/app/helpers/posts_helper.rb
module PostsHelper
end

assignment4/app/views/categories/_category.html.erb
<li>
	<h3><%= category.name %></h3>
	<ul>
		<li><%= link_to 'Edit', edit_category_url(category) %></li>
	</ul>
</li>

assignment4/app/views/categories/_form.html.erb
<% if @category.id.nil? %>
<% options = { method: :post, url: categories_path } %>
<% else %>
<% options = { method: :put, url: category_path(@category) } %>
<% end %>

<%= form_for(@category, options) do |f| %>
	<% if @category.errors.any? %>
		<ul>
		<% @category.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
		</ul>
	<% end %>

	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<%= f.submit "Submit" %>
<% end %>

assignment4/app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<%= render 'form' %>

assignment4/app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
<%= render partial: 'category', collection: @categories %>
</ul>

<ul>
	<li><a href="<%= new_post_path %>">Add post</a></li>
</ul>

assignment4/app/views/categories/new.html.erb
<h1>Category</h1>
<%= render 'form' %>

assignment4/app/views/categories/show.html.erb
<div>
	<h1><%= @category.name %></h1>
</div>

<ul>
	<li><%= link_to 'Edit', edit_category_url(@category) %></li>
	<!--<li><%= link_to 'Delete', @category, method: :delete, data: { confirm: 'Are you sure?' } %></li>-->
</ul>

assignment4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

assignment4/app/views/posts/_form.html.erb
<% if @post.id.nil? %>
<% options = { method: :post, url: posts_path } %>
<% else %>
<% options = { method: :put, url: post_path(@post) } %>
<% end %>

<%= form_for(@post, options) do |f| %>
	<% if @post.errors.any? %>
		<ul>
		<% @post.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
		</ul>
	<% end %>

	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>

	<div>
		<%= f.label :category %>
		<%= f.select :category, options_for_select(@categories.collect {|category| [category.name, category.id] }, selected: @post.category_id), { include_blank: true } %>
	</div>

	<%= f.submit "Submit" %>
<% end %>

assignment4/app/views/posts/_post.html.erb
<li>
	<h3><%= post.title %></h3>
	<p><%= post.description %></p>
	<div><a href="<%= category_url(post.category) %>"><%= post.category.name %></a></div>
	<ul>
		<li><%= link_to 'Edit', edit_post_url(post) %></li>
		<li><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	</ul>
</li>

assignment4/app/views/posts/edit.html.erb
<h1>Post Edit</h1>
<%= render 'form' %>

assignment4/app/views/posts/index.html.erb
<h1>Articles</h1>

<ul>
<%= render partial: 'post', collection: @posts %>
</ul>

assignment4/app/views/posts/new.html.erb
<h1>Post</h1>
<%= render 'form' %>

assignment4/app/views/posts/show.html.erb
<div>
	<h1><%= @post.title %></h1>
	<p><%= @post.description %></p>
</div>

<ul>
	<li><%= link_to 'Edit', edit_post_url(@post) %></li>
	<li><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>